# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d32cbe1da0ef15535f26db608c4853a01c4c8979a559a6ca4bf9add2d038d19610019344fa46a6eb522e835fefa6fde64b62b6ae755a04e68268440e3d4ad997

test:
  secret_key_base: 7b9a505374c56705d899ff9eefdc7b8f5558222920ea122a2195296b1b03cd6ec706b2c45520b53329f5cf872323594f41a916c91d8cfb8bb7c7e6a40e980acf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
